; Enable file uploads
file_uploads = On

; Maximum allowed size for uploaded files
upload_max_filesize = 200M

; Maximum size of POST data that PHP will accept (Must be larger than upload_max_filesize)
post_max_size = 200M

; Maximum execution time of each script, in seconds
max_execution_time = 300

; Maximum amount of time each script may spend parsing request data
max_input_time = 300

; Maximum memory a script may consume
memory_limit = 256M
