[program:writer]
command=/usr/local/bin/php -r 'while (true) { echo "[" . date("Y-m-d H:i:s") . "] [ INFO ] cron -> done\n"; flush(); sleep(3); }'
directory=/var/www/html
stdout_logfile=/var/www/html/cron-success.log
stderr_logfile=/var/www/html/cron-error.log

autostart=true
autorestart=true
startsecs=1
startretries=3
stdout_logfile_maxbytes=0
stderr_logfile_maxbytes=0

stopasgroup=true
killasgroup=true
